### PR TITLE
Final PR for docs, data types, cleanup and testing

### PR DESCRIPTION
**Pull request by tobias-urdin**
Here is the final PR that:

* Fixes all documentation and makes sure it follows Puppet Strings [1]
* Updates README.md to follow standardized format
* Adds CHANGELOG.md
* Adds Puppet data types
* Cleanup formatting of code
* Make sysctl::base private class
* Updates metadata.json to reflect only non-EOL operating systems
* Run spec testing for major supported operating systems

[1] https://puppet.com/docs/puppet/5.5/puppet_strings.html

Best regards
Tobias

### CODE REVIEW

**Comment by tobias-urdin** [comment]
IMO there is only one last thing to actually test and that would be using the newly provided `examples/init.pp` manifest to run actual module integration testing in TravisCI for the supported operating systems and then use serverspec [1] testing to validate the files and sysctl values in the operating system actually changed.

[1] https://serverspec.org/

*Oh and a note on this final PR is that Puppet 3 is now no longer supported and users must use v0.0.12 which we released earlier.*

Best regards
Tobias

**Comment by tobias-urdin** [comment]
ping @duritong

**Comment by tobias-urdin** [comment]
@duritong any update on this?

**Comment by tobias-urdin** [comment]
ping

**Comment by duritong** [comment]
Thank you very much. I am really sorry it took me so long to review and merge.

I would be very open to widen maintenance this module. I guess it would be good idea to migrate it to voxpupuli (https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli) and I would assume you already brought it into a good shape for that.

**Comment by tobias-urdin** [comment]
Thanks @duritong :)
I noticed that I did a minor error on the code formatting in the README, here is a quick fix https://github.com/duritong/puppet-sysctl/pull/43

**Pull request merged**
