### PR TITLE
FreeBSD 10 support - key: value

### PR DESCRIPTION
**Pull request by Thracky**

### CODE REVIEW

**Comment by Thracky** [comment]
Merging FreeBSD 10 sysctl support. sysctl output is in the following format in FreeBSD 10:
`net.inet.ip.forwarding: 0`

**Comment by duritong** [comment]
Hmmm, I need to fix the tests :-/

**Comment by duritong** [comment]
Thanks!

**Comment by Thracky** [comment]
No problem, happy to help :)

**Pull request merged**
